### ISSUE TITLE
Need your help:

### ISSUE THREAD

**Issue by rohini-gorige** [rajasoun/aws-cost-hub#22]
## 3. Configure gpg, pass and aws-vault

** step : 1. Generate a new GPG private key.**

Command: 

```
generate_gpg_keys
```

Output: 

<img width="690" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/102786626/168747226-db738e27-ea4f-43a2-914d-8076c69bf1bb.png">

**Comment by Ajithksin** [comment]
all are facing the same issue .

**Comment by Manuhali** [comment]
![image](https://user-images.githubusercontent.com/94919578/168748256-ec4ca9e7-9ec2-4987-9a09-69aefb946200.png)


Issue : **operation not permitted**
